namespace osrs_toolbox
{
    public class PlayerBosses
    {
        public BossData abyssal_sire { get; set; }
        public BossData alchemical_hydra { get; set; }
        public BossData amoxliatl { get; set; }
        public BossData araxxor { get; set; }
        public BossData artio { get; set; }
        public BossData barrows_chests { get; set; }
        public BossData bryophyta { get; set; }
        public BossData callisto { get; set; }
        public BossData calvarion { get; set; }
        public BossData cerberus { get; set; }
        public BossData chambers_of_xeric { get; set; }
        public BossData chambers_of_xeric_challenge_mode { get; set; }
        public BossData chaos_elemental { get; set; }
        public BossData chaos_fanatic { get; set; }
        public BossData commander_zilyana { get; set; }
        public BossData corporeal_beast { get; set; }
        public BossData crazy_archaeologist { get; set; }
        public BossData dagannoth_prime { get; set; }
        public BossData dagannoth_rex { get; set; }
        public BossData dagannoth_supreme { get; set; }
        public BossData deranged_archaeologist { get; set; }
        public BossData duke_sucellus { get; set; }
        public BossData general_graardor { get; set; }
        public BossData giant_mole { get; set; }
        public BossData grotesque_guardians { get; set; }
        public BossData hespori { get; set; }
        public BossData kalphite_queen { get; set; }
        public BossData king_black_dragon { get; set; }
        public BossData kraken { get; set; }
        public BossData kreearra { get; set; }
        public BossData kril_tsutsaroth { get; set; }
        public BossData lunar_chests { get; set; }
        public BossData mimic { get; set; }
        public BossData nex { get; set; }
        public BossData nightmare { get; set; }
        public BossData phosanis_nightmare { get; set; }
        public BossData obor { get; set; }
        public BossData phantom_muspah { get; set; }
        public BossData sarachnis { get; set; }
        public BossData scorpia { get; set; }
        public BossData scurrius { get; set; }
        public BossData skotizo { get; set; }
        public BossData sol_heredit { get; set; }
        public BossData spindel { get; set; }
        public BossData tempoross { get; set; }
        public BossData the_gauntlet { get; set; }
        public BossData the_corrupted_gauntlet { get; set; }
        public BossData the_hueycoatl { get; set; }
        public BossData the_leviathan { get; set; }
        public BossData the_royal_titans { get; set; }
        public BossData the_whisperer { get; set; }
        public BossData theatre_of_blood { get; set; }
        public BossData theatre_of_blood_hard_mode { get; set; }
        public BossData thermonuclear_smoke_devil { get; set; }
        public BossData tombs_of_amascut { get; set; }
        public BossData tombs_of_amascut_expert { get; set; }
        public BossData tzkal_zuk { get; set; }
        public BossData tztok_jad { get; set; }
        public BossData vardorvis { get; set; }
        public BossData venenatis { get; set; }
        public BossData vetion { get; set; }
        public BossData vorkath { get; set; }
        public BossData wintertodt { get; set; }
        public BossData yama { get; set; }
        public BossData zalcano { get; set; }
        public BossData zulrah { get; set; }
    }
}
